[package]
name = "code-core"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib"]

[dependencies]
pinyin = "0.10"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
